compatibility_date = "2024-08-18"
main = "src/index.ts"
minify = true
name = "uptime-worker"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
kv_namespaces = [{binding = "UPTIMEFLARE_STATE_V1", id = "e8e276b19a104f99817cc81950aadbc5"}]

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[triggers]
crons = ["0 * * * *"]